export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';
export const FETCH_PRODUCTS_SUCCES = 'FETCH_PRODUCTS_SUCCESS';

export const FETCH_SEARCH = 'FETCH_SEARCH';
export const FETCH_SEARCH_START = 'FETCH_SEARCH_START';
export const FETCH_SEARCH_FAIL = 'FETCH_SEARCH_FAIL';
export const FETCH_SEARCH_SUCCES = 'FETCH_SEARCH_SUCCESS';

export const FETCH_PRODUCT_INFO = 'FETCH_PRODUCT_INFO';
export const FETCH_PRODUCT_INFO_START = 'FETCH_PRODUCT_INFO_START';
export const FETCH_PRODUCT_INFO_FAIL = 'FETCH_PRODUCT_INFO_FAIL';
export const FETCH_PRODUCT_INFO_SUCCES = 'FETCH_PRODUCT_INFO_SUCCESS';

export const GET_CHECKOUT_START = 'GET_CHECKOUT_START';
export const GET_CHECKOUT_SUCCESS = 'GET_CHECKOUT_SUCCESS';
export const GET_CHECKOUT_FAIL = 'GET_CHECKOUT_FAIL';

export const DELETE_CHECKOUT = 'DELETE_CHECKOUT';
export const GET_CHECKOUT = 'GET_CHECKOUT';
export const SET_CHECKOUT = 'SET_CHECKOUT';

export const PURCHASE_INIT = 'PURCHASE_INIT';
export const PURCHASE_PRODUCT = 'PURCHASE_PRODUCT';
export const PURCHASE_PRODUCT_START = 'PURCHASE_PRODUCT_START';
export const PURCHASE_PRODUCT_SUCCESS = 'PURCHASE_PRODUCT_SUCCESS';
export const PURCHASE_PRODUCT_FAIL = 'PURCHASE_PRODUCT_FAIL';

export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_START = 'AUTH_START';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_REFRESH_TOKEN = 'AUTH_REFRESH_TOKEN';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';

export const RESET_PASSWORD_START = 'RESET_PASSWORD_START';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const RESET_PASSWORD = 'RESET_PASSWORD';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'